### PR TITLE
Updated code, June 2018.

### PR DESCRIPTION
**Pull request by julianx**

### CODE REVIEW

**Review by john-guerra — APPROVED** [review]

**Comment by john-guerra** [comment]
Thanks a lot

**Comment by john-guerra** [comment]
@julianx Traté de correr tu código y el scrapper no me funcionó...

`elTiestico6:carrosUsados aguerra$ scrapy runspider tuCarroScrapper.py -o usados.csv
2018-07-04 11:47:45 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-07-04 11:47:45 [scrapy.utils.log] INFO: Versions: lxml 3.4.4.0, libxml2 2.9.4, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) - [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)], pyOpenSSL 0.15.1 (OpenSSL 1.0.2o  27 Mar 2018), cryptography 2.0.3, Platform Darwin-17.6.0-x86_64-i386-64bit
2018-07-04 11:47:45 [scrapy.crawler] INFO: Overridden settings: {'SPIDER_LOADER_WARN_ONLY': True, 'FEED_FORMAT': 'csv', 'FEED_URI': 'usados.csv'}
2018-07-04 11:47:45 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2018-07-04 11:47:45 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-07-04 11:47:45 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-07-04 11:47:45 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-07-04 11:47:45 [scrapy.core.engine] INFO: Spider opened
2018-07-04 11:47:45 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-07-04 11:47:45 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-07-04 11:47:46 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://listado.tucarro.com.co/carros/renault/sandero-stepway/> from <GET http://listado.tucarro.com.co/carros/renault/sandero-stepway/>
2018-07-04 11:47:47 [scrapy.core.scraper] ERROR: Error downloading <GET https://listado.tucarro.com.co/carros/renault/sandero-stepway/>
Traceback (most recent call last):
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 67, in download_request
    return agent.download_request(request)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 331, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/web/client.py", line 1651, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/web/client.py", line 1635, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/web/client.py", line 1510, in endpointForURI
    uri.port)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/contextfactory.py", line 59, in creatorForNetloc
    return ScrapyClientTLSOptions(hostname.decode("ascii"), self.getContext())
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/contextfactory.py", line 56, in getContext
    return self.getCertificateOptions().getContext()
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/contextfactory.py", line 51, in getCertificateOptions
    acceptableCiphers=DEFAULT_CIPHERS)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/python/deprecate.py", line 792, in wrapped
    return wrappee(*args, **kwargs)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1583, in __init__
    self._options |= SSL.OP_SINGLE_DH_USE | SSL.OP_SINGLE_ECDH_USE
AttributeError: 'module' object has no attribute 'OP_SINGLE_ECDH_USE'
2018-07-04 11:47:47 [scrapy.core.engine] INFO: Closing spider (finished)
2018-07-04 11:47:47 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/exceptions.AttributeError': 1,
 'downloader/request_bytes': 504,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 629,
 'downloader/response_count': 1,
 'downloader/response_status_count/301': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 7, 4, 16, 47, 47, 202042),
 'log_count/DEBUG': 2,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 51847168,
 'memusage/startup': 51847168,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'start_time': datetime.datetime(2018, 7, 4, 16, 47, 45, 749494)}
2018-07-04 11:47:47 [scrapy.core.engine] INFO: Spider closed (finished)`

**Comment by julianx** [comment]
Y utilizando un json de salida y con esta forma qué dice? 

`scrapy crawl tuCarroScrapper -o out_file.json`

Otra cosa, puedes probar por favor con un Python 3 para ver si se queja igual? Intenté dejarlo compatible para ambos pero puede ser se haya roto para el viejo.

**Comment by julianx** [comment]
julianx@BMO:~ (01:07 PM) $ cd repos/usedCarsX/tucarro/
julianx@BMO:~/repos/usedCarsX/tucarro (01:07 PM) $ . ../../../pythonVirtualEnvs/scrappers/bin/activate
(scrappers) julianx@BMO:~/repos/usedCarsX/tucarro (01:08 PM) $ python --version
Python 3.6.1
(scrappers) julianx@BMO:~/repos/usedCarsX/tucarro (01:10 PM) $ scrapy crawl tuCarroScrapper -o all_cars_20180603.json
2018-07-04 13:10:23 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: tucarro)
2018-07-04 13:10:23 [scrapy.utils.log] INFO: Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) - [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-17.6.0-x86_64-i386-64bit
2018-07-04 13:10:23 [scrapy.crawler] INFO: Overridden settings: {'AUTOTHROTTLE_DEBUG': True, 'BOT_NAME': 'tucarro', 'EDITOR': 'vim', 'FEED_EXPORT_ENCODING': 'utf-8', 'FEED_FORMAT': 'json', 'FEED_URI': 'all_cars_20180603.json', 'HTTPCACHE_ENABLED': True, 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'tucarro.spiders', 'SPIDER_MODULES': ['tucarro.spiders']}

**Comment by john-guerra** [comment]
elTiestico6:carrosUsados aguerra$ scrapy crawl tuCarroScrapper -o out_file.json
Scrapy 1.5.0 - no active project

Unknown command: crawl

Qué versión tienes de scrapy?

**Comment by john-guerra** [comment]
`scrapy runspider tuCarroScrapper.py -o out_file.json
2018-07-04 13:10:59 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-07-04 13:10:59 [scrapy.utils.log] INFO: Versions: lxml 3.4.4.0, libxml2 2.9.4, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) - [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)], pyOpenSSL 0.15.1 (OpenSSL 1.0.2o  27 Mar 2018), cryptography 2.0.3, Platform Darwin-17.6.0-x86_64-i386-64bit
2018-07-04 13:10:59 [scrapy.crawler] INFO: Overridden settings: {'SPIDER_LOADER_WARN_ONLY': True, 'FEED_FORMAT': 'json', 'FEED_URI': 'out_file.json'}
2018-07-04 13:10:59 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2018-07-04 13:10:59 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-07-04 13:10:59 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-07-04 13:10:59 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-07-04 13:10:59 [scrapy.core.engine] INFO: Spider opened
2018-07-04 13:11:00 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-07-04 13:11:00 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-07-04 13:11:00 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://listado.tucarro.com.co/carros/renault/sandero-stepway/> from <GET http://listado.tucarro.com.co/carros/renault/sandero-stepway/>
2018-07-04 13:11:01 [scrapy.core.scraper] ERROR: Error downloading <GET https://listado.tucarro.com.co/carros/renault/sandero-stepway/>
Traceback (most recent call last):
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 67, in download_request
    return agent.download_request(request)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 331, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/web/client.py", line 1651, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/web/client.py", line 1635, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/web/client.py", line 1510, in endpointForURI
    uri.port)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/contextfactory.py", line 59, in creatorForNetloc
    return ScrapyClientTLSOptions(hostname.decode("ascii"), self.getContext())
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/contextfactory.py", line 56, in getContext
    return self.getCertificateOptions().getContext()
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/contextfactory.py", line 51, in getCertificateOptions
    acceptableCiphers=DEFAULT_CIPHERS)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/python/deprecate.py", line 792, in wrapped
    return wrappee(*args, **kwargs)
  File "/Users/aguerra/anaconda2/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1583, in __init__
    self._options |= SSL.OP_SINGLE_DH_USE | SSL.OP_SINGLE_ECDH_USE
AttributeError: 'module' object has no attribute 'OP_SINGLE_ECDH_USE'
2018-07-04 13:11:01 [scrapy.core.engine] INFO: Closing spider (finished)
2018-07-04 13:11:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/exceptions.AttributeError': 1,
 'downloader/request_bytes': 504,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 629,
 'downloader/response_count': 1,
 'downloader/response_status_count/301': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 7, 4, 18, 11, 1, 607850),
 'log_count/DEBUG': 2,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 52170752,
 'memusage/startup': 52170752,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'start_time': datetime.datetime(2018, 7, 4, 18, 11, 0, 11015)}
2018-07-04 13:11:01 [scrapy.core.engine] INFO: Spider closed (finished)
elTiestico6:carrosUsados aguerra$ 
`

**Pull request merged**
